### ISSUE TITLE
New _fromJson method without overriding

### ISSUE THREAD

**Issue by basters** [ikasparov/tsmodels#20]
I think what would be nice to create new extra method which will work like _fromJson, but instead of looking instance properties it could look only on passed object properties.

It can be helpful in case when we want to make partial update our model.

As example - you have intialized your model by values from JWT token. But after that you are going to the server and loading more info about user, so, you want to update model with new data.

I will try to create this feature...

**Comment by ikasparov** [comment]
solved  #21
